apiVersion: v1
entries:
  mayastor:
  - apiVersion: v2
    appVersion: 0.0.0
    created: "2024-02-28T11:52:40.572630266Z"
    dependencies:
    - name: etcd
      repository: https://charts.bitnami.com/bitnami
      version: 8.6.0
    - condition: base.jaeger.enabled
      name: jaeger-operator
      repository: https://jaegertracing.github.io/helm-charts
      version: 2.25.0
    - condition: loki-stack.enabled
      name: loki-stack
      repository: https://grafana.github.io/helm-charts
      version: 2.9.11
    - condition: eventing.enabled
      name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.14
    - condition: localpv-provisioner.enabled
      name: localpv-provisioner
      repository: https://openebs.github.io/dynamic-localpv-provisioner
      version: 3.5.0
    description: Mayastor Helm chart for Kubernetes
    digest: 2ee896f28d703f3e52fc8cd856be30a0ccd3318367cea2cba16dc82b6612d170
    name: mayastor
    type: application
    urls:
    - mayastor-0.0.0.tgz
    version: 0.0.0
generated: "2024-02-28T11:52:40.541880865Z"
